var fun={
    //请求头部
    getHeader:function(callback){
        $.ajax({
            url:"header.html",
            type:"get",
            success:function(result){
                callback(result);
            }
        })
    },
    //博文最新发布
    getIndex:function(callback){
        $.ajax({
            url:"http://127.0.0.1:5050/front/list",
            type:"get",
            dataType:"json",
            success:function(result){
               callback(result);
            }
        })
    },
    //博文详情页
    getDetails:function(callback){
        // 1.获取地址栏中传入的id值
        var id=location.href.split("?")[1]
        // 2.发送ajax
        $.ajax({
            url:"http://127.0.0.1:5050/front/details",
            type:"get",
            data:`id=${id}`,
            dataType:"json",
            success:function(result){
                callback(result);
            }
        })
    },
    //更多博文
    getMore:function(callback){
        $.ajax({
            url:"http://127.0.0.1:5050/front/indexMore",
            type:"get",
            dataType:"json",
            success:function(result){
                callback(result);
            }
        })
    },
    //学无止境推荐
    getLimitIndex:function(list){
        $.ajax({
            url:"http://127.0.0.1:5050/front/limit/list",
            type:"get",
            dataType:"json",
            success:function(result){
                list(result);
            }
        })
    },
    //学无止境更多
    getLimitMore:function(more){
        $.ajax({
            url:"http://127.0.0.1:5050/front/limit/more",
            type:"get",
            dataType:"json",
            success:function(result){
                more(result);
            }
        })
    },
    //我的足迹首页
    getTracksIndex:function(list){
        $.ajax({
            url:"http://127.0.0.1:5050/front/tracks/list",
            type:"get",
            dataType:"json",
            success:function(result){
                list(result);
            }
        })
    },
    //我的足迹更多
    getTracksMore:function(more){
        $.ajax({
            url:"http://127.0.0.1:5050/front/tracks/more",
            type:"get",
            dataType:"json",
            success:function(result){
                more(result);
            }
        })
    },
}